//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaludOcupacional_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CitaExamenResultado
    {
        public int idCitaExamenResultado { get; set; }
        public Nullable<int> idCita { get; set; }
        public Nullable<int> idExamenComponente { get; set; }
        public string resultado { get; set; }
        public Nullable<bool> estado { get; set; }
    
        public virtual Cita Cita { get; set; }
        public virtual ExamenComponente ExamenComponente { get; set; }
    }
}
