//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaludOcupacional_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CitaExamen
    {
        public int idCitaExamen { get; set; }
        public Nullable<int> idCita { get; set; }
        public Nullable<int> idExamen { get; set; }
        public Nullable<int> idMedico { get; set; }
        public Nullable<bool> estado { get; set; }
    
        public virtual Cita Cita { get; set; }
        public virtual Medico Medico { get; set; }
    }
}
