//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaludOcupacional_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamenComponente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExamenComponente()
        {
            this.CitaExamenResultado = new HashSet<CitaExamenResultado>();
        }
    
        public int idExamenComponente { get; set; }
        public Nullable<int> idExamen { get; set; }
        public string descripcionComponente { get; set; }
        public Nullable<bool> estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CitaExamenResultado> CitaExamenResultado { get; set; }
        public virtual Examen Examen { get; set; }
    }
}
