//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaludOcupacional_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PerfilMedicoExamen
    {
        public int idPerfilMedicoExamen { get; set; }
        public Nullable<int> idPerfilMedico { get; set; }
        public Nullable<int> idExamen { get; set; }
    
        public virtual Examen Examen { get; set; }
        public virtual PerfilMedico PerfilMedico { get; set; }
    }
}
