//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaludOcupacional_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona
    {
        public int idPersona { get; set; }
        public Nullable<int> idTipoPersona { get; set; }
        public string dni { get; set; }
        public string apellidoPaterno { get; set; }
        public string apellidoMaterno { get; set; }
        public string idUbigeo { get; set; }
        public Nullable<bool> estado { get; set; }
        public string nombre { get; set; }
        public byte[] Foto { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual Medico Medico { get; set; }
        public virtual Paciente Paciente { get; set; }
        public virtual TipoPersona TipoPersona { get; set; }
        public virtual Ubigeo Ubigeo { get; set; }
    }
}
