//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaludOcupacional_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cita
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cita()
        {
            this.CitaExamen = new HashSet<CitaExamen>();
            this.CitaExamenResultado = new HashSet<CitaExamenResultado>();
        }
    
        public int idCita { get; set; }
        public Nullable<int> idPersona { get; set; }
        public Nullable<int> idPerfilMedico { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> idEmpladoCrea { get; set; }
        public Nullable<int> idEmpleadoModifica { get; set; }
        public Nullable<int> idEmpleadoElimina { get; set; }
        public Nullable<bool> estado { get; set; }
    
        public virtual PerfilMedico PerfilMedico { get; set; }
        public virtual Paciente Paciente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CitaExamen> CitaExamen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CitaExamenResultado> CitaExamenResultado { get; set; }
    }
}
