//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaludOcupacional_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        public int idPersona { get; set; }
        public string nombreEmpleado { get; set; }
        public string clave { get; set; }
        public Nullable<bool> estado { get; set; }
        public string usuarioCrea { get; set; }
        public string usuarioModifica { get; set; }
        public Nullable<System.DateTime> fechaCrea { get; set; }
        public Nullable<System.DateTime> fechaModifica { get; set; }
    
        public virtual Persona Persona { get; set; }
    }
}
