//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaludOcupacional_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medico
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Medico()
        {
            this.CitaExamen = new HashSet<CitaExamen>();
        }
    
        public int idPersona { get; set; }
        public Nullable<int> nroColegiatura { get; set; }
        public string especialidad { get; set; }
        public Nullable<bool> estado { get; set; }
        public string usuarioCrea { get; set; }
        public string usuarioModifica { get; set; }
        public Nullable<System.DateTime> fechaCrea { get; set; }
        public Nullable<System.DateTime> fechaModifica { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CitaExamen> CitaExamen { get; set; }
        public virtual Persona Persona { get; set; }
    }
}
