//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaludOcupacional_Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SaludOcupacionalEntities : DbContext
    {
        public SaludOcupacionalEntities()
            : base("name=SaludOcupacionalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cita> Cita { get; set; }
        public virtual DbSet<CitaExamen> CitaExamen { get; set; }
        public virtual DbSet<CitaExamenResultado> CitaExamenResultado { get; set; }
        public virtual DbSet<Empleado> Empleado { get; set; }
        public virtual DbSet<Empresa> Empresa { get; set; }
        public virtual DbSet<Examen> Examen { get; set; }
        public virtual DbSet<ExamenComponente> ExamenComponente { get; set; }
        public virtual DbSet<Medico> Medico { get; set; }
        public virtual DbSet<Paciente> Paciente { get; set; }
        public virtual DbSet<PerfilMedico> PerfilMedico { get; set; }
        public virtual DbSet<PerfilMedicoExamen> PerfilMedicoExamen { get; set; }
        public virtual DbSet<Persona> Persona { get; set; }
        public virtual DbSet<TipoPersona> TipoPersona { get; set; }
        public virtual DbSet<Ubigeo> Ubigeo { get; set; }
    
        public virtual ObjectResult<usp_listarPacientes_Result> usp_listarPacientes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_listarPacientes_Result>("usp_listarPacientes");
        }
    }
}
