// Use DBML to define your database structure
// Docs: https://dbml.dbdiagram.io/docs
//hello mates

Table Persona {
  idPersona integer [primary key]
  idTipoPersona integer
  dni varchar(10)
  apellidoPaterno varchar(100)
  apellidoMaterno varchar(100)
  idUbigeo integer
  estado bit
}

Table TipoPersona {
  idTipoPersona integer [primary key]
  descripcion varchar(10)

}

Ref: Persona.idTipoPersona > TipoPersona.idTipoPersona


Table Paciente {
  idPersona integer [primary key]
  numeroDeHistoria varchar(20)
  estado bit
}

Ref: Persona.idPersona - Paciente.idPersona


Table Medico {
  idPersona integer [primary key]
  nroColegiatura integer
  especialiad varchar
  estado bit
}

Ref: Persona.idPersona - Medico.idPersona


Table Usuario {
  idPersona integer [primary key]
  nombreUsuario varchar(100)
  clave varchar()
  estado bit
}

Ref: Usuario.idPersona - Persona.idPersona

Table Empresa {
  idEmpresa integer [primary key]
  nombre varchar(100)
  RUC varchar (60) 
  idUbigeo integer
  estado bit
}

Table PerfilMedico {
  idPerfilMedico integer [primary key]
  idPersona integer
  idEmpresa integer
  descripcion varchar(100)
  estado bit
}

Table Examen {
  idExamen integer [primary key]
  nombre varchar
  estado bit
}


Table PerfilMedicoExamen {
  idPerfilMedicoExamen integer [primary key]
  idPerfilMedico integer
  idExamen integer
  estado bit
}

Ref: PerfilMedicoExamen.idPerfilMedico > PerfilMedico.idPerfilMedico
Ref: PerfilMedicoExamen.idExamen > Examen.idExamen

Table Cita {
  idCita integer [primary key]
  idPersona integer
  idPerfilMedico integer
  fecha datetime
  estado bit
}

Ref: Cita.idPerfilMedico > PerfilMedico.idPerfilMedico

Table CitaExamen {
  idCitaExamen integer [primary key]
  idCita integer
  idExamen integer
  estado bit
}

Ref: CitaExamen.idCita > Cita.idCita

Ref: Cita.idPersona > Paciente.idPersona


Table Ubigeo {
  idUbigeo int [primary key]
  estado bit
}



Table CitaExamenResultado {
  idCitaExamenResultado integer [primary key]  
  idCita integer
  idExamenComponente integer
  resultado varchar
  estado bit
}

Ref: CitaExamenResultado.idExamenComponente > ExamenComponente.idExamenComponente
Ref: CitaExamenResultado.idCita > Cita.idCita

Table ExamenComponente {
  idExamenComponente integer [primary key]
  idExamen integer
  descripcionComponente varchar
  estado bit
}

Ref: ExamenComponente.idExamen > Examen.idExamen 



Ref: PerfilMedico.idPersona > Paciente.idPersona 
Ref: PerfilMedico.idEmpresa > Empresa.idEmpresa
Ref: Persona.idUbigeo > Ubigeo.idUbigeo
Ref: Empresa.idUbigeo > Ubigeo.idUbigeo
